spring:
  application:
    name: wildcard-newsfeed-test

---
spring:
  datasource:
    url: jdbc:mysql://${DB_URL}/newsfeed
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      encoding: UTF-8

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        connection:
          CharSet: utf-8
          characterEncoding: utf-8
          useUnicode: true

logging.level:
  root: info
#  org.hibernate.SQL: debug
#  org.springframework.security: debug
#  org.springframework.web: debug

jwt:
  secret-key: ${JWT-SECRET-KEY}

server:
  port: ${SERVER_PORT}

---
spring:
  mail:
    host: smtp.gmail.com
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      maxFileSize: 300MB # 파일 하나의 최대 크기
      maxRequestSize: 1000MB  # 한 번에 최대 업로드 가능 용량
      location: /upload/

# S3
cloud:
  aws:
    s3:
      bucket: b15wildcard
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}